Repository Fraunhofer-AISEC/codyze, pull requests merged in 2021-12, with the labels that each got.

#369 Fix VSCode version and maintain revovate
  plugins/vscode/package.json
  renovate.json
Labels: bug, maintenance

#370 Fix renovate configuration
  renovate.json
Labels: bug

#371 Prepare release 2.0.0-beta1
  src/main/java/de/fraunhofer/aisec/codyze/Main.java
Labels: maintenance

#358 Rh/sarif compliency
  build.gradle.kts
  src/main/java/de/fraunhofer/aisec/codyze/Main.java
  src/main/java/de/fraunhofer/aisec/codyze/analysis/Finding.java
  src/main/java/de/fraunhofer/aisec/codyze/analysis/FindingDescription.kt
  src/main/java/de/fraunhofer/aisec/codyze/analysis/markevaluation/Evaluator.java
  src/main/java/de/fraunhofer/aisec/codyze/analysis/markevaluation/ExpressionEvaluator.java
  src/main/java/de/fraunhofer/aisec/codyze/analysis/wpds/TypestateAnalysis.kt
  src/main/java/de/fraunhofer/aisec/codyze/sarif/SarifInstantiator.kt
  src/main/resources/json/sarif-2.1.0.json
  src/test/java/de/fraunhofer/aisec/codyze/crymlin/FindingDescriptionTest.kt
  src/test/java/de/fraunhofer/aisec/codyze/crymlin/SarifInstantiatorTest.kt
  src/test/resources/unittests/.gitignore
  updateSARIF.md
Labels: enhancement

#388 Implementing a version provider
  build.gradle.kts
  src/main/java/de/fraunhofer/aisec/codyze/Main.java
Labels: enhancement
