Repository Fraunhofer-AISEC/codyze, pull requests merged in 2021-11, with the labels that each got.

#342 Use GitHub Action to setup Node.js
  .github/workflows/build.yml
Labels: bug, CI

#343 Reconfigure version range for vscode
  plugins/vscode/package.json
Labels: enhancement, dependencies

#350 Preserve version range for VSCode by bumping
  renovate.json
Labels: enhancement, CI

#357 Adjust renovate config for vscode plugin
  renovate.json
Labels: enhancement, CI

#361 Fixed getRegionByNode returning endLine instead of endColumn
  src/main/java/de/fraunhofer/aisec/codyze/analysis/utils/Utils.java
Labels: bug
