Repository Fraunhofer-AISEC/codyze, pull requests merged in 2024-04, with the labels that each got.

#828 Update detekt rule set
  buildSrc/src/main/kotlin/code-quality.gradle.kts
  codyze-specification-languages/coko/coko-dsl/src/test/kotlin/de/fraunhofer/aisec/codyze/specificationLanguages/coko/dsl/CokoCpgIntegrationTest.kt
  detekt.yml
Labels: maintenance

#836 Fix Windows path Issues in Coko tests
  codyze-backends/cpg/src/test/kotlin/de/fraunhofer/aisec/codyze/backends/cpg/CpgOptionGroupTest.kt
  codyze-backends/cpg/src/test/kotlin/de/fraunhofer/aisec/codyze/backends/cpg/FollowsEvaluationTest.kt
  codyze-backends/cpg/src/test/kotlin/de/fraunhofer/aisec/codyze/backends/cpg/ImplementationDslTest.kt
  codyze-backends/cpg/src/test/kotlin/de/fraunhofer/aisec/codyze/backends/cpg/NeverEvaluationTest.kt
  codyze-backends/cpg/src/test/kotlin/de/fraunhofer/aisec/codyze/backends/cpg/OnlyEvaluationTest.kt
  codyze-cli/src/test/kotlin/de/fraunhofer/aisec/codyze/cli/CodyzeCliTest.kt
  codyze-specification-languages/coko/coko-dsl/src/test/kotlin/de/fraunhofer/aisec/codyze/specificationLanguages/coko/dsl/CokoCpgIntegrationTest.kt
  codyze-specification-languages/coko/coko-dsl/src/test/kotlin/de/fraunhofer/aisec/codyze/specificationLanguages/coko/dsl/cli/CokoOptionGroupTest.kt
  codyze-specification-languages/coko/coko-dsl/src/test/kotlin/de/fraunhofer/aisec/codyze/specificationLanguages/coko/dsl/cli/ValidationTest.kt
Labels: bug

#837 Fix upgrade workflow
  .github/workflows/upgrade.yml
Labels: bug, CI

#843 Fix first start documentation
  README.md
  docs/Getting Started/configuration.md
Labels: documentation
